### ISSUE TITLE
How to pass the identifying without showing the image of capture code?

### ISSUE THREAD

**Issue by trim21** [chengluyu/sdu-chiangchen#1]

**Comment by chengluyu** [comment]
Oops. I forget to mention this in README. **The captcha image will be save as `check.png`.** Just load it with your favorite image viewer.

By the way if you’re using iTerm as your terminal emulator you can use the command `imgcat` to display the captcha image just in your terminal.

**Comment by chengluyu** [comment]
🤔️ Just now I found that I can’t book a seat with it because the JSON response schema of the server has changed. And I will fix this in the next few days.
